### ISSUE TITLE
[Question] Fetch only once database or at each time

### ISSUE THREAD

**Issue by DevKylian** [5am-code/laravel-notion-api#151]
Hello,

I use Notion as a database to make the content of my site manageable.

To retrieve the content I use "Notion::search()", but I have to use this function for each editable content which makes the page take 15 seconds to load (about 200 contents).

Is it possible to fetch the whole database once and then go and get the content ?
If yes, how to proceed?

Thanks in advance

**Comment by johguentner** [comment]
Hey @DevKylian !
Notion has limited the page-size for most requests (including search and db queries) to 100 results.
Also, they stated indirectly, that unspecific requests to the search-endpoint might take longer. (https://developers.notion.com/reference/search-optimizations-and-limitations)
I don't think Notion will change this behaviour in the near future, since it pretty much was like this since the beginning.
