### ISSUE TITLE
 Problem adding a page title

### ISSUE THREAD

**Issue by ThiagoCrepequer** [5am-code/laravel-notion-api#156]
Using the sample code from the documentation, the page title does not appear. The page is created normally, but the title seems to be ignored. The documentation states that creating a child page does not allow properties, but in the example, it seems that a title is being set.

```
$parentID = '';

$page = new Page();
$page->set('Name', Title::value('I was created from Laravel'));

$newPage = $this->notion->pages()->createInPage($parentID, $page);
```

I was expecting to create a new page with a predefined title.

**Comment by johguentner** [comment]
Hey @ThiagoCrepequer,

thank you for pointing that out!

Until recently, the default `title` attribute name was `Name`, however this has changed.

Now the default title attribute of a Page is `title`, unless defined otherwise (when the parent is a database).

So it should look like this:
```php
$parentID = '';

$page = new Page();
$page->set('title', Title::value('I was created from Laravel'));

$newPage = $this->notion->pages()->createInPage($parentID, $page);
```

Since this is no issue within the API, I'll mark this as closed. However I'll updated the docs asap, since this is confusing.

Thank you!

**Comment by johguentner** [comment]
### ✅  Docs have been updated to reflect this change
