### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by MasihTak** [5am-code/laravel-notion-api#171]
**Describe the bug**
The current documentation is wrong

**To Reproduce**
PHP v8.3.2
Laravel v10

```php
use \Notion;

Notion::databases()->find("8284f3ff77e24d4a939d19459e4d6bdc");
```

**Expected behavior**
Works without any issue

**Additional context**
First thing first if you use `use Notion; ` you will get this error "Undefined class Notion"
Instead, you should use `use FiveamCode\LaravelNotionApi\Notion;`

Second `Notion::databases()->find($databaseId);` you will get this error "Non-static method 'databases' should not be called statically "

The documentation is misleading and incomplete.

**Comment by johguentner** [comment]
In order to use the Notion-Facade correctly, please write the use as `use \Notion`.
If you do `use FiveamCode\LaravelNotionApi\Notion;` you use the actual class, which will try to call the methods statically, which will not work.

Please refer: https://laravel.com/docs/10.x/facades

In case you do not want to use the Facade, you can always create the instance yourself like this: https://notionforlaravel.com/#public-integration-o-auth
