### ISSUE TITLE
Page Creation example doesn't work

### ISSUE THREAD

**Issue by farez** [5am-code/laravel-notion-api#29]
Hi. Thanks for this great package!

**Describe the bug**
I'm trying to create a page in a database, and following the example here: https://5amco.de/docs/0.5.0/examples/update_create/create_page

Basically this didn't work because the method `createInDatabase` doesn't exist in the Notion class: `Notion::createInDatabase($databaseId, $page);` 

**To Reproduce**

Try to run `Notion::createInDatabase($databaseId, $page);` 

Laravel: 8.56

**Expected behavior**

A page is successfully created in Notion.

**Exceptions**

None.

**Additional context**

I did notice that the `Pages` class does have the `createInDatabase`, I tried the following code, but that returned a "Bad Request" error.

```
use FiveamCode\LaravelNotionApi\Notion;
use FiveamCode\LaravelNotionApi\Entities\Page;

$notion = new Notion($token);
$page = new Page();
$page->setTitle("Title", "Date Prop");
$notion->pages()->createInDatabase($dbId, $page);
```

**Comment by johguentner** [comment]
Hi @farez! Thanks for opening an issue!

Thank you so much for pointing out the error within the docs!
Initially we integrated ``createInDatabase(...)`` directly within the ``Notion::class``, however it's now - as you already pointed out - within the Endpoint ``Pages::class``. 
I'll fix the docs as soon as I can.

### Regarding 'Additional context'
If "Bad Request" is returned on ``$notion->pages()->createInDatabase($dbId, $page);``, there is usually a problem with the filled properties of the page. 

Please make sure to only fill properties, which exist within the given database. 
In your example you write ``$page->setTitle("Title", "Date Prop");``. 
The property-name 'Title' within your given database probably doesn't exist. 

The method-name ``$page->setTitle(...)`` is a little confusing, because you would expect to simply set the title of the page, however the property-name for the page-title of pages within databases can be rephrased within Notion, therefore you always need to address the property-name of the page-title.

For example, if you have called the page-title of your database 'Invoice Title', you need to write ``$page->setTitle("Invoice Title", "Invoice Customer B - Product X");``

We'll think about this matter for the next releases.

### Testing ``$notion->pages()->createInDatabase(...)``

I just tried out ``$notion->pages()->createInDatabase($dbId, $page);`` within out test-environment, and everything works as expected, as long as the filled properties are named correctly.  

If you have any questions about creating pages in databases, feel free to put them within this issue. 
I'll close the issue as soon as I have fixed the docs.

**Comment by farez** [comment]
Hey @johguentner thanks for that quick response!

You are right, there was a mismatch in the property name. It works now! Thank you so much.

This is a great package, thanks for your hard work. FYI, I'm using it to build notioninvoice.com.

Cheers,
Farez

**Comment by johguentner** [comment]
> Hey @johguentner thanks for that quick response!
> 
> You are right, there was a mismatch in the property name. It works now! Thank you so much.
> 
> This is a great package, thanks for your hard work. FYI, I'm using it to build notioninvoice.com.
> 
> Cheers,
> Farez

Just fixed and deployed the docs 🎯
Thank you again @farez for pointing out the wrong endpoint-call !
Looking forward to your great project ! 🚀

Closing the issue now.
