### ISSUE TITLE
Retrieve database entries in the manually-sorted order

### ISSUE THREAD

**Issue by jszobody** [5am-code/laravel-notion-api#66]
I'm trying to retrieve a simple list of pages in a database. In Notion, I have manually dragged and re-ordered these to be in a specific order. 

When I retrieve them simply as a collection...

```
Notion::database($databaseId)->query()->asCollection();
```

... and loop through, they are not in the same order as in Notion.

Yes I know I can specify explicit ordering, but I don't have any field/property that I can order on. My goal is to let the user manually drag to order items, and display them in that same order in my app. 

Is this possible?

**Comment by jszobody** [comment]
I see. Manual sorting is part of database views, and views are not supported currently.

https://stackoverflow.com/a/67915743/660694

Guess I'm out of luck. Will have to introduce a "Order By" database column for users to manage this, I suppose. If anyone has a better idea please let me know. =)

**Comment by johguentner** [comment]
Hey @jszobody,
thank you for describing your issue. 
As you already have seen, this is unfortunately not supported through the API at this point.

The only way I can see this could be accomplished, is if Notion will introduce an order-column-type, which records the order of a specific database. 
However, it does not sound like they would do something like that in the near future. I even assume they won't do anything like that, because they want to keep the frontend-database-view-structure and actual dataset-structure of the database separated, which I think is a good thing. 
But, let's see, maybe something is coming here in the next few months/years.

For some of my projects - where I use the API and need simple user-directed-sort - I usually have a simple index, or rather put a number in front of the name/title-column, which mostly does the sorting pretty straight forward. :-)
