### ISSUE TITLE
Support passing notion token to class constructor in addition to in an .env variable

### ISSUE THREAD

**Issue by danielh-official** [5am-code/laravel-notion-api#94]
**Is your feature request related to a problem? Please describe.**

For my needs, I don't know what the notion token will be. It will be included in a request passed to my app by the user that I will pass along to Notion's API. Having the only means of authentication as a .env variable makes establishing that workflow difficult.

**Describe the solution you'd like**

If no .env variable exists, the class constructor should throw an exception stating that a Notion token needs to be defined via the `NOTION_API_TOKEN` .env variable or passed to the constructor. The constructor can look something like:

```
protected string $notionApiToken;

public function __construct(string $notionApiToken = null) {
  $configuredNotionApiToken = config('laravel-notion-api.token');

  if(empty($configuredNotionApiToken) {
     if(empty($notionApiToken)) {
         throw new \Exception("Notion API token must be defined either in 'NOTION_API_TOKEN' .env variable or passed to constructor.")
     }

     $this->notionApiToken = $notionApiToken;
  } else {
     $this->notionApiToken = $configuredNotionApiToken;
  }
}
```

**Comment by johguentner** [comment]
Hi @danielh-official,

currently, this is not described in our docs (will be soon), however what you describe is already possible with the Laravel Notion API. 

Please check out https://github.com/5am-code/laravel-notion-api/blob/main/src/Notion.php.

As you can see, you can put the API token directly in the constructor, without using the .env (which is mostly used for internal projects)

Depending on what you want to do, you might want to check out https://socialiteproviders.com/Notion/#notion, since you (usually) should use OAuth, if you want to allow users to connect their Notion workspace to your app.
